### PR TITLE
fix prompt-toolkit mismatch

### PR DESCRIPTION
**Pull request by xaos11**
When trying to build this test branch I would get:

from prompt_toolkit.shortcuts import create_prompt_application, create_eventloop, create_prompt_layout, create_output ImportError: cannot import name create_prompt_application

When trying this solution:
`sudo pip install 'prompt-toolkit==1.0.15'
`
From:
https://github.com/jupyter/jupyter_console/issues/158

The error seems to go away. I don't know how to verify multi model selection is working, but the error is gone.

### CODE REVIEW

**Comment by vsoch** [comment]
I think the surefire thing to do (instead of guessing) would be to restore the exact versions of software for the originally built container:

```
backports-abc==0.4
backports.shutil-get-terminal-size==1.0.0
backports.ssl-match-hostname==3.5.0.1
certifi==2016.8.8
chardet==2.0.1
colorama==0.2.5
configparser==3.5.0
cycler==0.10.0
Cython==0.24.1
dask==0.10.2
decorator==3.4.0
docopt==0.6.2
entrypoints==0.2.2
functools32==3.2.3.post2
h5py==2.6.0
html5lib==0.999
ipykernel==4.4.1
ipython==5.0.0
ipython-genutils==0.1.0
ipywidgets==5.2.2
jedi==0.12.1
Jinja2==2.7.2
jsonschema==2.5.1
jupyter==1.0.0
jupyter-client==4.3.0
jupyter-console==5.0.0
jupyter-core==4.1.1
leveldb==0.193
MarkupSafe==0.18
matplotlib==1.5.1
mistune==0.7.3
mock==1.0.1
nbconvert==4.2.0
nbformat==4.1.0
networkx==1.11
nose==1.3.7
notebook==4.2.2
numpy==1.8.2
pandas==0.18.1
parso==0.3.1
pathlib2==2.1.0
pexpect==3.1
pickleshare==0.7.3
Pillow==2.3.0
prompt-toolkit==1.0.15
protobuf==3.0.0
ptpython==0.41
ptyprocess==0.5.1
pycurl==7.19.3
Pygments==2.1.3
pyparsing==2.1.6
python-dateutil==1.5
python-gflags==3.0.6
pytz==2016.6.1
PyYAML==3.11
pyzmq==14.0.1
qtconsole==4.2.1
requests==2.2.1
scikit-image==0.12.3
scipy==0.13.3
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.10.0
terminado==0.6
toolz==0.8.0
tornado==4.4.1
traitlets==4.2.2
urllib3==1.7.1
wcwidth==0.1.7
widgetsnbextension==1.2.6
```
would you care to try these in a requirements.txt, and if that fits the bill, we can update the Dockerfile using this updated set? Looks like you figured out the right version of prompt toolkit, which is great! Also for the record, the python:

```
# python --version
Python 2.7.6
```
Not super great, but this tends to be the case with a lot of ML work. Let me know how the updates above go.

**Comment by vsoch** [comment]
I don't see that the base container changed, so very likely the install of ptpython is what triggered any update to other dependencies (you could verify this when you build).

https://github.com/prompt-toolkit/ptpython/blob/master/setup.py#L22

**Comment by vsoch** [comment]
You could also pin the version of ptpython, since that triggered the update. That might be a simpler solution, and we have the versions in the comment here for the rest if it's ever needed (if the base container is updated).

**Comment by xaos11** [comment]
Honestly I'm more of a creator and less of a developer, so I probably won't be very successful. I have been running the docker image through a Node-RED loop (with JSONata expressions) for a couple of weeks, taking a random image from [Picsum](http://picsum.photos/) and a random fractal from [Sven Geier's copyleft art](http://www.sgeier.net/fractals/index.php) as a guide, getting some interesting results. I have even been able to process 2560 x 1440 images using almost 20 GB of RAM. 

image
This is the flow json file if you're interested:
[DeepDreamFlow.zip](https://github.com/vsoch/deepdream-docker/files/4269812/DeepDreamFlow.zip)

[Images that have been generated so far](https://1drv.ms/u/s!Am9JskkfNWwsgeNn8LheB8k39b-cVg?e=RQA2bK)

I think if random model selection was figured out, that could make this setup that much more interesting, as the default model can get a little repetitive with the dog-leg-eye thing that seems to manifest so often.

**Comment by vsoch** [comment]
Could you please test instead pinning the version of ptpython? It should result in the same container but not also update other dependencies that might have changed. You don’t need to do more than you have already done, just update the version of ptpython==0.41 and remove the line. After we check that I’d be happy to merge the PR.

**Comment by vsoch** [comment]
The images... wow! Beautiful! Do you plan to keep them online, want to link to from the repo to show off your work with the container?

**Comment by vsoch** [comment]
This looks great! As long as the base container remains constant, this should reproduce the build. Thanks for catching and fixing this.

**Comment by xaos11** [comment]
I do plan to keep them online and might do a blog post about the setup. If you think it would be a significant contribution to the project, I don't mind having them linked to so long as the original sources are attributed.

I look forward to trying other models... I've also been looking for a good Deep Style setup, but what I've tried so far hasn't worked out for me... yet. Another idea - running the Electric Sheep flame fractal animations through DeepDreamAnim.

**Comment by xaos11** [comment]
The files ending in ne2x.png have been run through https://hub.docker.com/r/alexjc/neural-enhance/
but I have stopped doing that for now as it takes extra time and I want to get a dual processing loop setup with a different machines. I'm going to split those out into a separate folder

**Comment by vsoch** [comment]
I agree that does make a [significant difference](https://github.com/alexjc/neural-enhance) but it's probably fairly computationally intensive. 

Your work is beautiful - I don't know if I can be of much help, but if you ever need someone that considers him/herself a developer, please reach out to me! I'm fairly good with containers, although these kind of ML containers tend to be very challenging because the state of python tooling is a constantly moving target.

**Pull request merged**
